# Generated by Django 5.2.13 on 2026-04-23 05:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Piloto, Mecânico de Motores', max_length=80, unique=True)),
                ('sigla', models.CharField(help_text='Ex: PLT, MEC', max_length=15, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição de responsabilidades e requisitos')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Permanência, Sobreaviso, Serviço Administrativo', max_length=60, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Explicação do tipo de escala')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_escala',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoIndisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Férias, Licença Médica, Missão', max_length=60, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('exclui_do_sorteio', models.BooleanField(default=True, help_text='Se True, militar com este tipo não pode ser escalado')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Indisponibilidade',
                'db_table': 'tipo_indisponibilidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da OM (ex: 1º Batalhão de Infantaria)', max_length=120)),
                ('sigla', models.CharField(help_text='Sigla/código único (ex: BtlInf01)', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('regimento', 'Regimento'), ('batalhao', 'Batalhão'), ('companhia', 'Companhia'), ('pelotao', 'Pelotão'), ('secao', 'Seção'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('endereco', models.CharField(blank=True, help_text='Localização da OM', max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato da OM', max_length=254)),
                ('comandante', models.CharField(blank=True, help_text='Nome do comandante atual', max_length=120)),
                ('ativo', models.BooleanField(default=True, help_text='Soft delete')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('om_superior', models.ForeignKey(blank=True, help_text='OM que controla esta (ex: um Batalhão está sob um Regimento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_subordinadas', to='escalas.organizacaomilitar')),
            ],
            options={
                'verbose_name_plural': 'Organizações Militares',
                'db_table': 'organizacao_militar',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Divisão de Pessoal, Divisão de Operações', max_length=100)),
                ('sigla', models.CharField(help_text='Ex: DPE, DOP', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição das responsabilidades')),
                ('chefe', models.CharField(blank=True, help_text='Nome do chefe da divisão', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao_militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes', to='escalas.organizacaomilitar')),
            ],
            options={
                'db_table': 'divisao',
                'ordering': ['organizacao_militar', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Soldado, Cabo, Sargento, Tenente', max_length=60, unique=True)),
                ('sigla', models.CharField(help_text='Ex: Sd, Cb, Sgt, Tte', max_length=10, unique=True)),
                ('ordem_hierarquica', models.PositiveIntegerField(help_text='Ordem na hierarquia (1=menor, 20=maior)', unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'posto',
                'ordering': ['ordem_hierarquica'],
                'indexes': [models.Index(fields=['ordem_hierarquica'], name='posto_ordem_h_b6611c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_guerra', models.CharField(help_text='Nome de guerra do militar (aparece nas escalas)', max_length=40)),
                ('nome_completo', models.CharField(help_text='Nome completo para registros oficiais', max_length=120)),
                ('cpf', models.CharField(help_text='CPF sem formatação', max_length=11, unique=True)),
                ('matricula', models.CharField(help_text='Matrícula militar/ID único da OM', max_length=20, unique=True)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento')),
                ('ativo', models.BooleanField(default=True, help_text='Soft delete para manter histórico de escalas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('divisao', models.ForeignKey(blank=True, help_text='Divisão dentro da OM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militares', to='escalas.divisao')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militares', to='escalas.especialidade')),
                ('organizacao_militar', models.ForeignKey(help_text='OM à qual o militar pertence', on_delete=django.db.models.deletion.PROTECT, related_name='militares', to='escalas.organizacaomilitar')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='militares', to='escalas.posto')),
            ],
            options={
                'db_table': 'militar',
                'ordering': ['organizacao_militar', 'nome_guerra'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Primeira data indisponível')),
                ('data_fim', models.DateField(help_text='Última data indisponível')),
                ('observacao', models.TextField(blank=True, help_text='Motivo adicional')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='escalas.militar')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indisponibilidades', to='escalas.tipoindisponibilidade')),
            ],
            options={
                'db_table': 'indisponibilidade',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Preto, Vermelho, Roxo, Normal', max_length=40)),
                ('cor_hex', models.CharField(default='#000000', help_text='Cor em hex (ex: #000000)', max_length=7)),
                ('descricao', models.TextField(blank=True, help_text="Ex: 'Segunda a sexta - dias úteis'")),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao_militar', models.ForeignKey(help_text='Cada OM pode customizar seus tipos de serviço', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servico', to='escalas.organizacaomilitar')),
            ],
            options={
                'db_table': 'tipo_servico',
                'ordering': ['organizacao_militar', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Quadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(help_text='Ano da contagem')),
                ('quantidade', models.PositiveIntegerField(default=0, help_text='Total de serviços realizados')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrinhos', to='escalas.militar')),
                ('tipo_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrinhos', to='escalas.tipoescala')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrinhos', to='escalas.tiposervico')),
            ],
            options={
                'db_table': 'quadrinho',
                'ordering': ['ano', '-quantidade'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do dia')),
                ('origem_tipo', models.CharField(choices=[('AUTO', 'Automático (segunda a sexta / sábado e domingo)'), ('MANUAL', 'Manual (feriado móvel ou ajuste especial)')], default='AUTO', help_text='Como o tipo foi definido', max_length=10)),
                ('observacao', models.CharField(blank=True, help_text="Ex: 'Carnaval 2025', 'Feriado antecipado'", max_length=120)),
                ('organizacao_militar', models.ForeignKey(help_text='Cada OM tem seu próprio calendário', on_delete=django.db.models.deletion.CASCADE, related_name='calendario_dias', to='escalas.organizacaomilitar')),
                ('tipo_servico', models.ForeignKey(help_text='Tipo de serviço para este dia', on_delete=django.db.models.deletion.PROTECT, related_name='dias_calendario', to='escalas.tiposervico')),
            ],
            options={
                'db_table': 'calendario_dia',
                'ordering': ['organizacao_militar', 'data'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('admin_om', 'Administrador da OM'), ('escalante', 'Escalante (Gera escalas)'), ('militar', 'Militar (Consulta apenas)'), ('gerente', 'Gerente (Leitura e relatórios)')], default='militar', help_text='Nível de acesso no sistema', max_length=20)),
                ('eh_militar', models.BooleanField(default=False, help_text='Indica se este usuário também é um registro de Militar')),
                ('ativo', models.BooleanField(default=True, help_text='Soft delete para preservar histórico')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos de permissão', related_name='usuario_customizado_set', to='auth.group', verbose_name='groups')),
                ('militar_associado', models.OneToOneField(blank=True, help_text='Se eh_militar=True, referencia ao Militar correspondente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='escalas.militar')),
                ('om_principal', models.ForeignKey(blank=True, help_text='OM onde o usuário trabalha principalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_principais', to='escalas.organizacaomilitar')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas', related_name='usuario_customizado_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario_customizado',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(help_text='Mês (1-12)')),
                ('ano', models.PositiveIntegerField(help_text='Ano (ex: 2025)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_publicacao', models.DateTimeField(blank=True, help_text='Data em que foi publicada', null=True)),
                ('observacao', models.TextField(blank=True, help_text='Observações gerais sobre a escala')),
                ('organizacao_militar', models.ForeignKey(help_text='Cada OM tem suas próprias escalas', on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escalas.organizacaomilitar')),
                ('tipo_escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='escalas.tipoescala')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_criadas', to='escalas.usuariocustomizado')),
            ],
            options={
                'db_table': 'escala',
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='EscalaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, help_text="Ex: 'Substitui...' ou 'Justificativa de troca'", max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('calendario_dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_itens', to='escalas.calendariodia')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='escalas.escala')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_itens', to='escalas.militar')),
            ],
            options={
                'db_table': 'escala_item',
                'ordering': ['calendario_dia__data', 'militar__nome_guerra'],
                'indexes': [models.Index(fields=['escala', 'militar'], name='escala_item_escala__a6f5d6_idx'), models.Index(fields=['calendario_dia'], name='escala_item_calenda_c3a627_idx')],
                'unique_together': {('escala', 'calendario_dia')},
            },
        ),
        migrations.AddIndex(
            model_name='organizacaomilitar',
            index=models.Index(fields=['sigla'], name='organizacao_sigla_60db32_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacaomilitar',
            index=models.Index(fields=['ativo', 'om_superior'], name='organizacao_ativo_f97856_idx'),
        ),
        migrations.AddIndex(
            model_name='divisao',
            index=models.Index(fields=['organizacao_militar', 'ativo'], name='divisao_organiz_608b2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='divisao',
            unique_together={('organizacao_militar', 'sigla')},
        ),
        migrations.AddIndex(
            model_name='militar',
            index=models.Index(fields=['organizacao_militar', 'ativo'], name='militar_organiz_f5d724_idx'),
        ),
        migrations.AddIndex(
            model_name='militar',
            index=models.Index(fields=['nome_guerra'], name='militar_nome_gu_154a13_idx'),
        ),
        migrations.AddIndex(
            model_name='militar',
            index=models.Index(fields=['cpf'], name='militar_cpf_0f4939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='militar',
            unique_together={('organizacao_militar', 'matricula')},
        ),
        migrations.AddIndex(
            model_name='indisponibilidade',
            index=models.Index(fields=['militar', 'data_inicio', 'data_fim'], name='indisponibi_militar_a82511_idx'),
        ),
        migrations.AddIndex(
            model_name='tiposervico',
            index=models.Index(fields=['organizacao_militar', 'ativo'], name='tipo_servic_organiz_84f77d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiposervico',
            unique_together={('organizacao_militar', 'nome')},
        ),
        migrations.AddIndex(
            model_name='quadrinho',
            index=models.Index(fields=['militar', 'ano'], name='quadrinho_militar_4626ec_idx'),
        ),
        migrations.AddIndex(
            model_name='quadrinho',
            index=models.Index(fields=['tipo_escala', 'tipo_servico', 'ano'], name='quadrinho_tipo_es_d407f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quadrinho',
            unique_together={('militar', 'tipo_escala', 'tipo_servico', 'ano')},
        ),
        migrations.AddIndex(
            model_name='calendariodia',
            index=models.Index(fields=['organizacao_militar', 'data'], name='calendario__organiz_f5cf93_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariodia',
            index=models.Index(fields=['data', 'tipo_servico'], name='calendario__data_9c3366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendariodia',
            unique_together={('organizacao_militar', 'data')},
        ),
        migrations.AddIndex(
            model_name='usuariocustomizado',
            index=models.Index(fields=['perfil', 'ativo'], name='usuario_cus_perfil_112a50_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariocustomizado',
            index=models.Index(fields=['om_principal', 'ativo'], name='usuario_cus_om_prin_59a928_idx'),
        ),
        migrations.AddIndex(
            model_name='escala',
            index=models.Index(fields=['organizacao_militar', 'status'], name='escala_organiz_4fdc87_idx'),
        ),
        migrations.AddIndex(
            model_name='escala',
            index=models.Index(fields=['ano', 'mes'], name='escala_ano_4d190d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('organizacao_militar', 'tipo_escala', 'mes', 'ano')},
        ),
    ]
