# Generated by Django 6.0.4 on 2026-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacaomilitar',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brasão/distintivo da OM (substitui a estrela amarela na navbar)', null=True, upload_to='oms/logos/'),
        ),
    ]
