# Generated by Django 6.0.4 on 2026-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_organizacaomilitar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrinho',
            name='ajuste_inicial',
            field=models.PositiveIntegerField(default=0, help_text='Saldo inicial vindo do controle anterior (legado, antes deste sistema)'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('previsao', 'Previsão'), ('publicada', 'Escala (Oficial)'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='quadrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Serviços contabilizados pelo sistema (pode ser sobrescrito manualmente)'),
        ),
    ]
