# Generated by Django 6.0.4 on 2026-05-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_quadrinho_ajuste_inicial_alter_escala_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuário Django vinculado a este militar (para auto-serviço)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militar', to=settings.AUTH_USER_MODEL),
        ),
    ]
