# Generated by Django 6.0.4 on 2026-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0006_ponteiroescala'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaitem',
            name='forcar_escala',
            field=models.BooleanField(default=False, help_text='Quando marcado, ignora a regra de folga mínima para este item. Use para situações excepcionais (serviços consecutivos por necessidade operacional).'),
        ),
        migrations.AddField(
            model_name='tipoescala',
            name='folga_minima_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Folga mínima específica para este tipo de escala (horas). Se vazio, usa a configuração global da OM.', null=True),
        ),
    ]
