# Generated by Django 6.0.4 on 2026-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0007_tipo_escala_folga_escala_item_forcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='data_ultima_promocao',
            field=models.DateField(blank=True, help_text='Data da última promoção ao posto atual. Usada como critério de antiguidade quando dois militares têm o mesmo posto: a data mais antiga indica o militar mais antigo.', null=True),
        ),
    ]
