# Generated by Django 6.0.4 on 2026-05-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0008_add_data_ultima_promocao_to_militar'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaitem',
            name='substituto',
            field=models.ForeignKey(blank=True, help_text='Militar que substituiu o escalado original na Escala Oficial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_como_substituto', to='escalas.militar'),
        ),
    ]
