# Generated by Django 5.2.1 on 2026-05-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0010_tipo_escala_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoescala',
            name='bloquear_pos_ferias',
            field=models.BooleanField(default=True, help_text='Se ativado, bloqueia serviços dentro do período de folga mínima após o retorno de férias/indisponibilidade.', verbose_name='Bloquear pós-férias'),
        ),
        migrations.AlterField(
            model_name='configuracaoescala',
            name='bloquear_pre_ferias',
            field=models.BooleanField(default=True, help_text='Se ativado, bloqueia serviços que terminariam dentro do período de folga mínima antes do início de uma férias/indisponibilidade.', verbose_name='Bloquear pré-férias'),
        ),
        migrations.AlterField(
            model_name='configuracaoescala',
            name='duracao_servico_horas',
            field=models.PositiveIntegerField(default=24, help_text='Duração padrão de um serviço em horas. Usado para calcular quando o militar fica livre após o serviço.', verbose_name='Duração do serviço (horas)'),
        ),
        migrations.AlterField(
            model_name='configuracaoescala',
            name='folga_minima_horas',
            field=models.PositiveIntegerField(default=48, help_text='Horas mínimas de folga exigidas após um serviço ou retorno de férias/indisponibilidade antes de novo serviço. Exemplo: 48 = dois dias de folga.', verbose_name='Folga mínima (horas)'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição das responsabilidades', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição de responsabilidades e requisitos', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='posto',
            name='ordem_hierarquica',
            field=models.PositiveIntegerField(help_text='Ordem na hierarquia (1=menor, 20=maior)', unique=True, verbose_name='Ordem hierárquica'),
        ),
        migrations.AlterField(
            model_name='tipoescala',
            name='descricao',
            field=models.TextField(blank=True, help_text='Explicação do tipo de escala', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoescala',
            name='folga_minima_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Folga mínima específica para este tipo de escala (horas). Se vazio, usa a configuração global da OM.', null=True, verbose_name='Folga mínima (horas)'),
        ),
        migrations.AlterField(
            model_name='tipoescala',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável gerada automaticamente do nome (ex: permanencia). Não altere após criação para não quebrar links existentes.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoindisponibilidade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='descricao',
            field=models.TextField(blank=True, help_text="Ex: 'Segunda a sexta - dias úteis'", verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='perfil',
            field=models.CharField(choices=[('admin_om', 'Administrador da OM'), ('chefe', 'Chefe (Publica escalas)'), ('adjunto', 'Adjunto (Publica escalas)'), ('escalante', 'Escalante (Gera escalas)'), ('militar', 'Militar (Consulta apenas)'), ('gerente', 'Gerente (Leitura e relatórios)')], default='militar', help_text='Nível de acesso no sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='TrocaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle', models.CharField(help_text='Número de controle no formato DD/MM/AAAA', max_length=20, unique=True)),
                ('tipo_troca', models.CharField(choices=[('simples', 'Troca Simples'), ('mutua', 'Troca Mútua')], default='simples', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('homologada', 'Homologada')], default='pendente', max_length=20)),
                ('escala_status', models.CharField(choices=[('previsao', 'Previsão'), ('publicada', 'Escala Publicada')], help_text='Indica se a troca foi feita na previsão ou escala publicada', max_length=20)),
                ('data_servico_sai', models.DateField(help_text='Data do serviço do militar que sai')),
                ('data_servico_sai_2', models.DateField(blank=True, help_text='Data do serviço do segundo militar', null=True)),
                ('motivo', models.TextField(help_text='Motivo da solicitação de troca')),
                ('aprovada_militar_sai', models.BooleanField(default=False, help_text='Militar que sai aprovou a troca')),
                ('aprovada_militar_entra', models.BooleanField(default=False, help_text='Militar que entra aprovou a troca (ou None se ainda não selecionou)')),
                ('aprovada_militar_sai_2', models.BooleanField(default=False, help_text='Segundo militar que sai aprovou a troca')),
                ('aprovada_militar_entra_2', models.BooleanField(default=False, help_text='Segundo militar que entra aprovou a troca')),
                ('aprobada_escalante', models.BooleanField(blank=True, help_text='Aprovação do escalante (True=Aprovada, False=Reprovada, Null=Pendente)', null=True)),
                ('data_aprovacao_escalante', models.DateTimeField(blank=True, help_text='Data da aprovação/reprovação pelo escalante', null=True)),
                ('escalante_observacao', models.TextField(blank=True, help_text='Observação do escalante ao aprovar/reprovar')),
                ('homologada', models.BooleanField(blank=True, help_text='Homologação do Chefe/Adjunto (True=Homologada, False=Reprovada, Null=Pendente)', null=True)),
                ('data_homologacao', models.DateTimeField(blank=True, help_text='Data da homologação pelo Chefe/Adjunto', null=True)),
                ('homologacao_observacao', models.TextField(blank=True, help_text='Observação do Chefe/Adjunto ao homologar')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('militar_entra', models.ForeignKey(blank=True, help_text='Militar que vai assumir o serviço', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trocas_como_entra', to='escalas.militar')),
                ('militar_entra_2', models.ForeignKey(blank=True, help_text='Segundo militar que entra (para troca mútua)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trocas_como_entra_2', to='escalas.militar')),
                ('militar_sai', models.ForeignKey(help_text='Militar que vai sair do serviço', on_delete=django.db.models.deletion.PROTECT, related_name='trocas_como_sai', to='escalas.militar')),
                ('militar_sai_2', models.ForeignKey(blank=True, help_text='Segundo militar que sai (para troca mútua)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trocas_como_sai_2', to='escalas.militar')),
                ('organizacao_militar', models.ForeignKey(help_text='OM onde a troca foi solicitada', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_servico', to='escalas.organizacaomilitar')),
                ('tipo_escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trocas_servico', to='escalas.tipoescala')),
                ('usuario_chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_homologadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_escalante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_aprovadas_escalante', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'troca_servico',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['organizacao_militar', 'status'], name='troca_servi_organiz_02ba14_idx'), models.Index(fields=['militar_sai', 'data_criacao'], name='troca_servi_militar_0ac55c_idx'), models.Index(fields=['status', 'data_criacao'], name='troca_servi_status_9b2380_idx')],
            },
        ),
    ]
