# Generated by Django 6.0.4 on 2026-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0011_troca_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='username_ldap',
            field=models.CharField(blank=True, default='', help_text='Username de rede (sAMAccountName) para login via LDAP/Active Directory. Deve ser igual ao username cadastrado em UsuarioCustomizado.', max_length=64),
        ),
    ]
