# Generated by Django 6.0.4 on 2026-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0012_add_username_ldap_to_militar'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='tipos_escala',
            field=models.ManyToManyField(blank=True, help_text='Tipos de escala nos quais este militar participa. Apenas militares vinculados a um tipo de escala serão considerados na geração automática daquele tipo.', related_name='militares_participantes', to='escalas.tipoescala'),
        ),
    ]
