"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tv=yz++fhm@$vipya_&q0#5uh*8bp0-pk%!(a2jxa8yzy4ck#9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
    'https://*.replit.app',
    'https://*.kirk.replit.dev',
    'https://*.picard.replit.dev',
]

AUTH_USER_MODEL = 'escalas.UsuarioCustomizado'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escalas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'escalas.context_processors.om_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Uploads (logos das OMs etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===========================================================================
# AUTENTICAÇÃO LDAP / ACTIVE DIRECTORY
# ===========================================================================
# Para habilitar o login via LDAP:
#   1. Instale: pip install django-auth-ldap
#   2. Descomente as configurações abaixo e ajuste os valores
#   3. O backend CustomLDAPBackend (core/backend.py) garante que apenas
#      usuários previamente cadastrados no sistema consigam autenticar via LDAP
#
# Fluxo de autenticação:
#   - Login → CustomLDAPBackend verifica se username existe localmente
#   - Se existir: autentica via LDAP (valida senha no AD)
#   - Se não existir: ModelBackend tenta senha local (fallback)
# ===========================================================================

# import ldap
# from django_auth_ldap.config import LDAPSearch

# AUTH_LDAP_SERVER_URI = "ldap://10.100.0.1:389"
# AUTH_LDAP_BIND_DN = "cn=django,ou=XXXX,dc=xxxx,dc=dddd"
# AUTH_LDAP_BIND_PASSWORD = "XXXXXXXXXXXXX"

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "ou=XXXX,dc=xxxx,dc=dddd",
#     ldap.SCOPE_SUBTREE,
#     "(sAMAccountName=%(user)s)",   # Active Directory
#     # "(uid=%(user)s)",            # OpenLDAP / alternativa
# )

# AUTH_LDAP_USER_ATTR_MAP = {
#     "username":   "sAMAccountName",
#     "first_name": "name",
#     "last_name":  "physicalDeliveryOfficeName",
#     "email":      "mail",
# }

# Backends ativos quando LDAP estiver habilitado:
# AUTHENTICATION_BACKENDS = [
#     "core.backend.CustomLDAPBackend",   # LDAP primeiro (requer usuário local)
#     "django.contrib.auth.backends.ModelBackend",  # fallback senha local
# ]

# Configurações opcionais do django-auth-ldap:
# AUTH_LDAP_ALWAYS_UPDATE_USER = True   # Sincroniza atributos do AD a cada login
# AUTH_LDAP_CACHE_TIMEOUT = 3600        # Cache de grupo em segundos
